"""Create a dashboard page to display the energy production and the predictions.

- the energy production is obtained from the RTE API
- the predictions are computed using the weather data and linear models.
"""
from energy_forecast.energy import ECO2MixDownloader
from energy_forecast import ROOT_DIR
from energy_forecast.meteo import ArpegeSimpleAPI, memory
from energy_forecast.enr_production_model import ENRProductionModel
import pandas as pd
import streamlit as st
import altair as alt
alt.renderers.set_embed_options(time_format_locale="fr-FR", format_locale="fr-FR")

@memory.cache
def compute_my_prodiction(date)->pd.DataFrame:
    """Estimate the power generated by eolien.

    Use the data from :func:`get_region_swind` and a linear model to estimate the power generated by wind turbines.

    Parameters
    ----------
    date : str
        The date at which the power is estimated.

    Returns
    -------
    pd.DataFrame
        The power generated by solar panels for each hour of the day.
        The columns are ["time", "eolien_power"]
    """
    wind_data = ArpegeSimpleAPI(date).departement_wind()
    sun_data = ArpegeSimpleAPI(date).departement_sun()
    my_model = ENRProductionModel.load(filename="model_departements.pkl")
    
    predictions = my_model.predict(sun_data, wind_data)
    return predictions

@memory.cache
def compute_energy(date:str):
    """Concatenate the energy production data with the predictions.

    Energy production data is downloaded from RTE and the predictions are computed using the models from :func:`compute_data_pv_power` and :func:`compute_data_eolien`.

    TODO
    ----
    - Use the RTE API instead of the File Zip Download for Realtime data

    Parameters
    ----------
    date : str
        The date at which the energy production is estimated.

    Returns
    -------
    pd.DataFrame
        The energy production for each region and the predictions for solar and wind power.
        The columns are:
        - ``"time"``: the time of the data (pd.Timestamp)
        - ``"Eolien"``: the wind power production (historical data from RTE)
        - ``"Solaire"``: the solar power production (historical data from RTE)
        - ``"PV Prediction"``: the solar power production prediction (from linear model using weather date)
        - ``"Eolien Prediction"``: the wind power production prediction (from linear model using weather date)

    """
    predictions = compute_my_prodiction(date)
    
    current_year = pd.Timestamp(date).year
    r = ECO2MixDownloader(year=current_year)
    r.download()
    energy =  r.read_file()

    energy = energy[["Eolien", "Solaire"]]
    energy.rename(columns={"Eolien": "Eolien Production", "Solaire": "PV Production"}, inplace=True)
    offset_days = 5
    history_start = pd.Timestamp(date) - pd.Timedelta(f"{offset_days} days")
    energy = energy[history_start:]
    energy.index = energy.index.tz_localize("Europe/Paris").tz_convert("UTC").tz_localize(None)
    energy = pd.concat([
        energy,
        predictions.rename(columns={"sun": "PV Prediction",
                                    "wind": "Eolien Prediction"})
    ], axis=1).reset_index(names="time")

    return energy

if __name__ == "__main__":

    date_input = st.sidebar.date_input("Date", pd.Timestamp.now())

    # date = pd.Timestamp.now().strftime("%Y-%m-%d")
    energy = compute_energy(date_input)
    # keep only full hours, needed to plot the data without empty spaces
    print(energy)
    energy = energy[energy["time"].dt.minute == 0]

    st.title("Prévision de production ENR")
    st.markdown("Cette page affiche les prévisions de production d'énergie renouvelable pour la date sélectionnée."
                " Les données sont obtenues à partir de [RTE](https://www.rte-france.com/eco2mix/la-production-delectricite-en-temps-reel).")


    energy_long = energy.melt(id_vars="time", var_name="source", value_name="power")
    eolen_long = energy_long[energy_long["source"].str.contains("Eolien")]
    pv_long = energy_long[energy_long["source"].str.contains("PV")]

    eolen_title = alt.Title("Production Eolien",
                            subtitle="Production historique et prévisionnelle")

    eolen_chart = alt.Chart(eolen_long, title=eolen_title).mark_line().encode(
        x=alt.X("time:T", title="Date"),
        y=alt.Y("power:Q", title="Production (MW)"),
        color=alt.Color("source:N", title="Type de production"),
    )

    st.altair_chart(eolen_chart,
                    use_container_width=True
                )

    sun_title = alt.Title("Production Solaire",
                          subtitle="Production historique et prévisionnelle")
    sun_chart = alt.Chart(pv_long, title=sun_title).mark_line().encode(
        x=alt.X("time:T", title="Date"),
        y=alt.Y("power:Q", title="Production (MW)"),
        color=alt.Color("source:N", title="Type de production"),
    )
    st.altair_chart(sun_chart,
                    use_container_width=True
                )
