"""This module contains the different pages of the dashboard.

Stremlit automatically detects the different pages of the dashboard and add them to the sidebar of the main page.

The main page is generated by the :mod:`src.energy_forecast.dashboard.Accueil` module."""