
#: List of all the regions in France
#: Ordered by as the mask ``"mask_france_regions.nc"``.
region_names = ["Île-de-France",
                "Centre-Val de Loire",
                "Bourgogne-Franche-Comté",
                "Normandie",
                "Hauts-de-France",
                "Grand Est",
                "Pays de la Loire",
                "Bretagne",
                "Nouvelle-Aquitaine",
                "Occitanie",
                "Auvergne-Rhône-Alpes",
                "Provence-Alpes-Côte d'Azur",
                "Corse"
                ]

#: List of all the departments in France
#: Ordered by as the mask ``"mask_france_departments.nc"``.
departement_names = ["Aisne",
                "Aube",
                "Calvados",
                "Cantal",
                "Eure-et-Loir",
                "Ille-et-Vilaine",
                "Jura",
                "Landes",
                "Loire",
                "Loiret",
                "Lot-et-Garonne",
                "Meuse",
                "Orne",
                "Pas-de-Calais",
                "Puy-de-Dôme",
                "Bas-Rhin",
                "Haut-Rhin",
                "Seine-Maritime",
                "Yonne",
                "Seine-Saint-Denis",
                "Alpes-de-Haute-Provence",
                "Hautes-Alpes",
                "Ardèche",
                "Ardennes",
                "Ariège",
                "Charente-Maritime",
                "Corrèze",
                "Dordogne",
                "Eure",
                "Indre-et-Loire",
                "Lozère",
                "Nièvre",
                "Oise",
                "Pyrénées-Atlantiques",
                "Rhône",
                "Saône-et-Loire",
                # "Paris",
                "Yvelines",
                "Tarn",
                "Tarn-et-Garonne",
                "Var",
                "Vendée",
                "Haute-Vienne",
                "Vosges",
                "Hauts-de-Seine",
                "Allier",
                "Alpes-Maritimes",
                "Aude",
                "Corse-du-Sud",
                "Côtes-d'Armor",
                "Creuse",
                "Doubs",
                "Finistère",
                "Gard",
                "Gironde",
                "Indre",
                "Isère",
                "Marne",
                "Haute-Marne",
                "Moselle",
                "Hautes-Pyrénées",
                "Pyrénées-Orientales",
                "Savoie",
                "Haute-Savoie",
                "Seine-et-Marne",
                "Vaucluse",
                "Vienne",
                "Val-de-Marne",
                "Ain",
                "Aveyron",
                "Bouches-du-Rhône",
                "Charente",
                "Cher",
                "Haute-Corse",
                "Côte-d'Or",
                "Drôme",
                "Haute-Garonne",
                "Gers",
                "Hérault",
                "Haute-Loire",
                "Loire-Atlantique",
                "Lot",
                "Maine-et-Loire",
                "Manche",
                "Morbihan",
                "Nord",
                "Haute-Saône",
                "Sarthe",
                "Somme",
                "Essonne",
                "Val-d'Oise",
                "Loir-et-Cher",
                "Mayenne",
                "Meurthe-et-Moselle",
                "Deux-Sèvres",
                ]

france_bounds = {
"min_lon": -4.79542,
"max_lon": 9.55996,
"min_lat": 41.36484,
"max_lat": 51.089,
}
