# Generated by Django 5.1.1 on 2024-09-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecastMeanDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_time', models.DateTimeField()),
                ('department', models.CharField(choices=[('Aisne ', 'Aisne '), ('Aube ', 'Aube '), ('Calvados ', 'Calvados '), ('Cantal ', 'Cantal '), ('Eure-et-Loir ', 'Eure-et-Loir '), ('Ille-et-Vilaine ', 'Ille-et-Vilaine '), ('Jura ', 'Jura '), ('Landes ', 'Landes '), ('Loire ', 'Loire '), ('Loiret ', 'Loiret '), ('Lot-et-Garonne ', 'Lot-et-Garonne '), ('Meuse ', 'Meuse '), ('Orne ', 'Orne '), ('Pas-de-Calais ', 'Pas-de-Calais '), ('Puy-de-Dôme ', 'Puy-de-Dôme '), ('Bas-Rhin ', 'Bas-Rhin '), ('Haut-Rhin ', 'Haut-Rhin '), ('Seine-Maritime ', 'Seine-Maritime '), ('Yonne ', 'Yonne '), ('Seine-Saint-Denis ', 'Seine-Saint-Denis '), ('Alpes-de-Haute-Provence ', 'Alpes-de-Haute-Provence '), ('Hautes-Alpes ', 'Hautes-Alpes '), ('Ardèche ', 'Ardèche '), ('Ardennes ', 'Ardennes '), ('Ariège ', 'Ariège '), ('Charente-Maritime ', 'Charente-Maritime '), ('Corrèze ', 'Corrèze '), ('Dordogne ', 'Dordogne '), ('Eure ', 'Eure '), ('Indre-et-Loire ', 'Indre-et-Loire '), ('Lozère ', 'Lozère '), ('Nièvre ', 'Nièvre '), ('Oise ', 'Oise '), ('Pyrénées-Atlantiques ', 'Pyrénées-Atlantiques '), ('Rhône ', 'Rhône '), ('Saône-et-Loire ', 'Saône-et-Loire '), ('Paris ', 'Paris '), ('Yvelines ', 'Yvelines '), ('Tarn ', 'Tarn '), ('Tarn-et-Garonne ', 'Tarn-et-Garonne '), ('Var ', 'Var '), ('Vendée ', 'Vendée '), ('Haute-Vienne ', 'Haute-Vienne '), ('Vosges ', 'Vosges '), ('Hauts-de-Seine ', 'Hauts-de-Seine '), ('Allier ', 'Allier '), ('Alpes-Maritimes ', 'Alpes-Maritimes '), ('Aude ', 'Aude '), ('Corse-du-Sud ', 'Corse-du-Sud '), ("Côtes-d'Armor ", "Côtes-d'Armor "), ('Creuse ', 'Creuse '), ('Doubs ', 'Doubs '), ('Finistère ', 'Finistère '), ('Gard ', 'Gard '), ('Gironde ', 'Gironde '), ('Indre ', 'Indre '), ('Isère ', 'Isère '), ('Marne ', 'Marne '), ('Haute-Marne ', 'Haute-Marne '), ('Moselle ', 'Moselle '), ('Hautes-Pyrénées ', 'Hautes-Pyrénées '), ('Pyrénées-Orientales ', 'Pyrénées-Orientales '), ('Savoie ', 'Savoie '), ('Haute-Savoie ', 'Haute-Savoie '), ('Seine-et-Marne ', 'Seine-et-Marne '), ('Vaucluse ', 'Vaucluse '), ('Vienne ', 'Vienne '), ('Val-de-Marne ', 'Val-de-Marne '), ('Ain ', 'Ain '), ('Aveyron ', 'Aveyron '), ('Bouches-du-Rhône ', 'Bouches-du-Rhône '), ('Charente ', 'Charente '), ('Cher ', 'Cher '), ('Haute-Corse ', 'Haute-Corse '), ("Côte-d'Or ", "Côte-d'Or "), ('Drôme ', 'Drôme '), ('Haute-Garonne ', 'Haute-Garonne '), ('Gers ', 'Gers '), ('Hérault ', 'Hérault '), ('Haute-Loire ', 'Haute-Loire '), ('Loire-Atlantique ', 'Loire-Atlantique '), ('Lot ', 'Lot '), ('Maine-et-Loire ', 'Maine-et-Loire '), ('Manche ', 'Manche '), ('Morbihan ', 'Morbihan '), ('Nord ', 'Nord '), ('Haute-Saône ', 'Haute-Saône '), ('Sarthe ', 'Sarthe '), ('Somme ', 'Somme '), ('Essonne ', 'Essonne '), ("Val-d'Oise ", "Val-d'Oise "), ('Loir-et-Cher ', 'Loir-et-Cher '), ('Mayenne ', 'Mayenne '), ('Meurthe-et-Moselle ', 'Meurthe-et-Moselle ')], max_length=50)),
                ('horizon_forecast', models.CharField(choices=[('D0', 'D0'), ('D1', 'D1'), ('D2', 'D2'), ('D3', 'D3')], max_length=2)),
                ('sun_flux', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('temperature', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['valid_time', 'horizon_forecast'], name='core_weathe_valid_t_82976e_idx')],
            },
        ),
    ]
